exp:
  algorithm_name: rmappo
  experiment_name: acc5v1_EscapeZone
  seed: 1
  num_env_steps: 2000000 # total environment steps to train

# Environment settings (common)
env:
  env_name: Pursuit-Zone
  world_size: 200
  episode_length: 400 # max steps per episode
  max_hunters_num: 5
  hunters_in_zone: true

  neighbor_N: 3

  target_policy_source: learn # Choices: ["learn", "patrol", "Random"]
  target_switch_interval: 10

Hunter:
  perception_radius: -1
  control_mode: acceleration  # Choices: ["acceleration", "velocity"]

Target: 
  perception_radius: -1
  control_mode: acceleration

# UAV pursuit scenario settings
reward:
  # Collision Penalty
  target_collision_penalty: 30.0
  collision_penalty_k: 5.0
  collision_penalty_cap: 20.0
  safe_zone_penalty_scale: 0.1
  
  # Base chase reward
  base_far_scale: 0.2
  base_near_scale: 1.0
  base_streak_scale: 0.1
  base_streak_cap: 30

  # Escape Gap
  escape_gap_enable: true
  escape_gap_hunter_reward_scale: 1.0
  escape_gap_target_reward_scale: 0.3
  escape_radius: 35.0

  # Capture reward
  hunter_capture_reward: 15.0
  target_captured_penalty: 12.0

  # Speed Penalty
  speed_penalty: 0.02

# Model/network settings
model:
  policy_share: true # whether all agents share the same policy
  hidden_size: 64
  layer_N: 1
  use_recurrent_policy: true


# Optimizer settings
optim:
  lr: 0.0005
  critic_lr: 0.0005
  opti_eps: 0.00001
  weight_decay: 0

# Learning rate schedule
schedule:
  use_linear_lr_decay: true

logging:
  log_gif: true         # 训练阶段是否按规则保存GIF

eval:
  eval_episode_length: 600
  fixed_tasks_file: config/eval_tasks/patrol_tasks_h8_n100.yaml

domain_randomization:
  train_split:
    enable: false
    regen_interval_episode: 20
    regen_prob: 1.0
    hunter_count_choices: [1, 2, 3, 4, 5]
    seed_range: [1, 99999]
    target_policy_choices: ["learn", "patrol", "random"]
    patrol_name_choices: ["all"]

# Pretrained model
pretrained:
  model_dir: null
