exp:
  algorithm_name: mappo
  experiment_name: vel3v1
  seed: 1
  cuda: true
  cuda_deterministic: true
  n_training_threads: 2
  n_rollout_threads: 5
  n_eval_rollout_threads: 10
  n_render_rollout_threads: 1
  num_env_steps: 1000000

env:
  env_name: seen_hunter_only
  world_size: 100
  episode_length: 200
  dt: 0.1
  num_hunters: 3
  num_explorers: 0

  capture_dis: 20
  capture_step: 10

  collision_dis: 3

  target_pos_init_guidance_step: 10
  target_pos_guidance: true
  noisy_target_pos_std: 2
  noisy_target_vel_std: 10

  target_policy_source: learn
  target_patrol_path: datasets/patrol_routes.json
  target_patrol_names: ["square", "ring"]
  target_switch_interval: 10

Hunter:
  perception_radius: -1
  max_velo: 20
  safe_dis: 15
  control_mode: velocity  # Choices: ["acceleration", "velocity"]
  max_acc: 8
  max_turn_angle: 10
  min_turn_limit_velo: 3.0

Explorer:
  perception_radius: -1
  max_velo: 10
  safe_dis: 15

Target: 
  perception_radius: -1
  max_velo: 12
  safe_dis: 15
  control_mode: velocity
  max_acc: 6
  max_turn_angle: 10
  min_turn_limit_velo: 3.0

reward:
  # Collision Penalty
  collision_penalty_k: 20.0
  collision_penalty_cap: 200.0
  safe_zone_penalty_scale: 0.1
  
  # Base chase reward
  base_far_scale: 0.2
  base_near_scale: 1.0
  base_streak_scale: 0.1
  base_streak_cap: 30

  # Capture reward
  hunter_capture_reward: 15.0
  target_captured_penalty: 12.0

  # Speed Penalty
  speed_penalty: 0.02
  
  # Explorer Penalty
  lost_target_penalty: 0.1
  lost_target_penalty_age_scale: 0.02


# Model/network settings
model:
  policy_share: true # whether all agents share the same policy
  use_centralized_V: true # centralized value function
  stacked_frames: 1
  use_stacked_frames: false
  hidden_size: 64
  layer_N: 1
  use_ReLU: true
  use_popart: false
  use_valuenorm: true
  use_feature_normalization: true
  use_orthogonal: true
  gain: 0.01
  use_naive_recurrent_policy: false
  use_recurrent_policy: false
  recurrent_N: 1
  data_chunk_length: 10

# Optimizer settings
optim:
  lr: 0.0005
  critic_lr: 0.0005
  opti_eps: 0.00001
  weight_decay: 0

# PPO settings
ppo:
  ppo_epoch: 15
  use_clipped_value_loss: true
  clip_param: 0.2
  num_mini_batch: 1
  entropy_coef: 0.01
  value_loss_coef: 1
  use_max_grad_norm: true
  max_grad_norm: 10.0
  use_gae: true
  gamma: 0.99
  gae_lambda: 0.95
  use_proper_time_limits: false
  use_huber_loss: true
  use_value_active_masks: true
  use_policy_active_masks: true
  huber_delta: 10.0

# Learning rate schedule
schedule:
  use_linear_lr_decay: false

# Save/log settings
logging:
  save_interval: 20     # ckpts 保存episode间隔
  log_interval: 10      # 打印中间结果episode间隔
  gif_frame_interval: 5       # GIF抽帧间隔
  gif_frame_duration: 0.1

# Evaluation settings
eval:
  use_eval: true
  val_interval: 20
  scenario_suite_val: datasets/val
  scenario_suite_test: datasets/test

# Render settings
render:
  save_gifs: false
  use_render: false
  render_episodes: 5
  ifi: 0.1

# Pretrained model
pretrained:
  model_dir: null
