exp:
  algorithm_name: mappo
  experiment_name: default_experiment
  seed: 1
  cuda: true
  cuda_deterministic: true
  n_training_threads: 2
  n_rollout_threads: 1
  n_eval_rollout_threads: 1
  n_render_rollout_threads: 1
  num_env_steps: 1000000

env:
  env_name: uav_pursuit
  world_size: 400
  episode_length: 200
  dt: 0.1
  num_hunters: 3
  num_explorers: 0
  capture_dis: 10
  capture_step: 10
  collision_dis: 3
  target_pos_init_guidance_step: 10
  target_pos_guidance: true
  noisy_target_pos_std: 10
  noisy_target_vel_std: 10
  target_policy_source: train
  target_patrol_path: datasets/patrol_routes.json
  target_patrol_names: []
  target_patrol_switch_interval: 10

Hunter:
  perception_radius: 25
  max_velo: 20

Explorer:
  perception_radius: 80
  max_velo: 10

Target:
  perception_radius: 40
  max_velo: 12

reward:
  collision_penalty_k: 5.0
  lost_target_penalty: 0.1
  lost_target_penalty_age_scale: 0.02
  gif_interval: 10
  gif_frame_duration: 0.1
  speed_penalty: 0.02

model:
  policy_share: true
  use_centralized_V: true
  stacked_frames: 1
  use_stacked_frames: false
  hidden_size: 64
  layer_N: 1
  use_ReLU: true
  use_popart: false
  use_valuenorm: true
  use_feature_normalization: true
  use_orthogonal: true
  gain: 0.01
  use_naive_recurrent_policy: false
  use_recurrent_policy: false
  recurrent_N: 1
  data_chunk_length: 10

optim:
  lr: 0.0005
  critic_lr: 0.0005
  opti_eps: 0.00001
  weight_decay: 0

ppo:
  ppo_epoch: 15
  use_clipped_value_loss: true
  clip_param: 0.2
  num_mini_batch: 1
  entropy_coef: 0.01
  value_loss_coef: 1
  use_max_grad_norm: true
  max_grad_norm: 10.0
  use_gae: true
  gamma: 0.99
  gae_lambda: 0.95
  use_proper_time_limits: false
  use_huber_loss: true
  use_value_active_masks: true
  use_policy_active_masks: true
  huber_delta: 10.0

schedule:
  use_linear_lr_decay: false

logging:
  save_interval: 1
  log_interval: 5

eval:
  use_eval: false
  val_interval: 100
  val_episodes: 5
  scenario_suite_val: datasets/val
  scenario_suite_test: datasets/test

render:
  save_gifs: false
  use_render: false
  render_episodes: 5
  ifi: 0.1

pretrained:
  model_dir: null
